// Generated by `supabase gen types typescript` from the live schema.
// Do not edit by hand. Regenerate after migrations.
/* eslint-disable */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      archive_item_sources: {
        Row: {
          archive_item_id: string
          connector_account_id: string | null
          created_at: string
          id: string
          metadata_json: Json
          source_created_at: string | null
          source_deleted_at: string | null
          source_item_id: string | null
          source_modified_at: string | null
          source_url_if_safe: string | null
        }
        Insert: {
          archive_item_id: string
          connector_account_id?: string | null
          created_at?: string
          id?: string
          metadata_json?: Json
          source_created_at?: string | null
          source_deleted_at?: string | null
          source_item_id?: string | null
          source_modified_at?: string | null
          source_url_if_safe?: string | null
        }
        Update: {
          archive_item_id?: string
          connector_account_id?: string | null
          created_at?: string
          id?: string
          metadata_json?: Json
          source_created_at?: string | null
          source_deleted_at?: string | null
          source_item_id?: string | null
          source_modified_at?: string | null
          source_url_if_safe?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "archive_item_sources_archive_item_id_fkey"
            columns: ["archive_item_id"]
            isOneToOne: false
            referencedRelation: "archive_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "archive_item_sources_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      archive_items: {
        Row: {
          archived_at: string | null
          checksum_sha256: string
          created_at: string
          created_at_source: string | null
          file_size: number
          id: string
          metadata_json: Json
          mime_type: string
          modified_at_source: string | null
          original_filename: string
          owner_id: string
          status: Database["public"]["Enums"]["archive_item_status"]
          storage_key: string
          storage_provider: string
          type: Database["public"]["Enums"]["archive_item_type"]
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          checksum_sha256: string
          created_at?: string
          created_at_source?: string | null
          file_size?: number
          id?: string
          metadata_json?: Json
          mime_type: string
          modified_at_source?: string | null
          original_filename: string
          owner_id: string
          status?: Database["public"]["Enums"]["archive_item_status"]
          storage_key: string
          storage_provider: string
          type: Database["public"]["Enums"]["archive_item_type"]
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          checksum_sha256?: string
          created_at?: string
          created_at_source?: string | null
          file_size?: number
          id?: string
          metadata_json?: Json
          mime_type?: string
          modified_at_source?: string | null
          original_filename?: string
          owner_id?: string
          status?: Database["public"]["Enums"]["archive_item_status"]
          storage_key?: string
          storage_provider?: string
          type?: Database["public"]["Enums"]["archive_item_type"]
          updated_at?: string
        }
        Relationships: []
      }
      archive_job_items: {
        Row: {
          attempts: number
          claimed_at: string | null
          claimed_by: string | null
          connector_account_id: string | null
          created_at: string
          filename: string | null
          id: string
          job_id: string
          last_error: string | null
          mime_type: string | null
          next_attempt_at: string
          size_bytes: number | null
          source_etag: string | null
          source_item_id: string
          status: string
          storage_key: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          claimed_at?: string | null
          claimed_by?: string | null
          connector_account_id?: string | null
          created_at?: string
          filename?: string | null
          id?: string
          job_id: string
          last_error?: string | null
          mime_type?: string | null
          next_attempt_at?: string
          size_bytes?: number | null
          source_etag?: string | null
          source_item_id: string
          status?: string
          storage_key?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          claimed_at?: string | null
          claimed_by?: string | null
          connector_account_id?: string | null
          created_at?: string
          filename?: string | null
          id?: string
          job_id?: string
          last_error?: string | null
          mime_type?: string | null
          next_attempt_at?: string
          size_bytes?: number | null
          source_etag?: string | null
          source_item_id?: string
          status?: string
          storage_key?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "archive_job_items_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "archive_job_items_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "archive_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      archive_jobs: {
        Row: {
          attempts: number
          bytes_processed: number
          claimed_at: string | null
          claimed_by: string | null
          completed_at: string | null
          connector_account_id: string | null
          created_at: string
          cursor: Json | null
          error_code: string | null
          id: string
          items_archived: number
          items_discovered: number
          items_failed: number
          items_processed: number
          items_skipped: number
          job_type: Database["public"]["Enums"]["job_type"]
          last_error: string | null
          next_archive_at: string | null
          retry_count: number
          run_at: string
          safe_error_message: string | null
          scheduled_at: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["job_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          bytes_processed?: number
          claimed_at?: string | null
          claimed_by?: string | null
          completed_at?: string | null
          connector_account_id?: string | null
          created_at?: string
          cursor?: Json | null
          error_code?: string | null
          id?: string
          items_archived?: number
          items_discovered?: number
          items_failed?: number
          items_processed?: number
          items_skipped?: number
          job_type: Database["public"]["Enums"]["job_type"]
          last_error?: string | null
          next_archive_at?: string | null
          retry_count?: number
          run_at?: string
          safe_error_message?: string | null
          scheduled_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          bytes_processed?: number
          claimed_at?: string | null
          claimed_by?: string | null
          completed_at?: string | null
          connector_account_id?: string | null
          created_at?: string
          cursor?: Json | null
          error_code?: string | null
          id?: string
          items_archived?: number
          items_discovered?: number
          items_failed?: number
          items_processed?: number
          items_skipped?: number
          job_type?: Database["public"]["Enums"]["job_type"]
          last_error?: string | null
          next_archive_at?: string | null
          retry_count?: number
          run_at?: string
          safe_error_message?: string | null
          scheduled_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "archive_jobs_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      connector_accounts: {
        Row: {
          archive_frequency: Database["public"]["Enums"]["archive_frequency"]
          authorization_expires_at: string | null
          connected_at: string | null
          connector_key: string
          created_at: string
          cursor_state_encrypted: string | null
          display_name: string | null
          id: string
          last_attempt_at: string | null
          last_successful_archive_at: string | null
          provider_account_identifier: string | null
          status: Database["public"]["Enums"]["connector_account_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          archive_frequency?: Database["public"]["Enums"]["archive_frequency"]
          authorization_expires_at?: string | null
          connected_at?: string | null
          connector_key: string
          created_at?: string
          cursor_state_encrypted?: string | null
          display_name?: string | null
          id?: string
          last_attempt_at?: string | null
          last_successful_archive_at?: string | null
          provider_account_identifier?: string | null
          status?: Database["public"]["Enums"]["connector_account_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          archive_frequency?: Database["public"]["Enums"]["archive_frequency"]
          authorization_expires_at?: string | null
          connected_at?: string | null
          connector_key?: string
          created_at?: string
          cursor_state_encrypted?: string | null
          display_name?: string | null
          id?: string
          last_attempt_at?: string | null
          last_successful_archive_at?: string | null
          provider_account_identifier?: string | null
          status?: Database["public"]["Enums"]["connector_account_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      connector_credentials: {
        Row: {
          ciphertext: string
          connector_account_id: string
          created_at: string
          id: string
          kind: string
          scheme: string
          updated_at: string
        }
        Insert: {
          ciphertext: string
          connector_account_id: string
          created_at?: string
          id?: string
          kind: string
          scheme: string
          updated_at?: string
        }
        Update: {
          ciphertext?: string
          connector_account_id?: string
          created_at?: string
          id?: string
          kind?: string
          scheme?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "connector_credentials_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_oauth_clients: {
        Row: {
          client_id: string
          client_secret_hash: string
          created_at: string
          id: string
          name: string | null
          redirect_uris: string[]
        }
        Insert: {
          client_id: string
          client_secret_hash: string
          created_at?: string
          id?: string
          name?: string | null
          redirect_uris?: string[]
        }
        Update: {
          client_id?: string
          client_secret_hash?: string
          created_at?: string
          id?: string
          name?: string | null
          redirect_uris?: string[]
        }
        Relationships: []
      }
      meta_oauth_codes: {
        Row: {
          client_id: string
          code_hash: string
          connector_account_id: string | null
          created_at: string
          expires_at: string
          id: string
          redirect_uri: string
          scope: string | null
          used: boolean
          user_id: string
        }
        Insert: {
          client_id: string
          code_hash: string
          connector_account_id?: string | null
          created_at?: string
          expires_at: string
          id?: string
          redirect_uri: string
          scope?: string | null
          used?: boolean
          user_id: string
        }
        Update: {
          client_id?: string
          code_hash?: string
          connector_account_id?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          redirect_uri?: string
          scope?: string | null
          used?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_oauth_codes_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_oauth_tokens: {
        Row: {
          access_expires_at: string
          access_token_hash: string
          client_id: string
          connector_account_id: string | null
          created_at: string
          id: string
          refresh_expires_at: string | null
          refresh_token_hash: string | null
          revoked: boolean
          scope: string | null
          user_id: string
        }
        Insert: {
          access_expires_at: string
          access_token_hash: string
          client_id: string
          connector_account_id?: string | null
          created_at?: string
          id?: string
          refresh_expires_at?: string | null
          refresh_token_hash?: string | null
          revoked?: boolean
          scope?: string | null
          user_id: string
        }
        Update: {
          access_expires_at?: string
          access_token_hash?: string
          client_id?: string
          connector_account_id?: string | null
          created_at?: string
          id?: string
          refresh_expires_at?: string | null
          refresh_token_hash?: string | null
          revoked?: boolean
          scope?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_oauth_tokens_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_transfer_jobs: {
        Row: {
          bytes_received: number
          completed_at: string | null
          connector_account_id: string | null
          created_at: string
          id: string
          items_duplicate: number
          items_failed: number
          items_new: number
          items_seen: number
          received_at: string | null
          requested_at: string | null
          source_type: string
          status: string
          transfer_kind: string
          updated_at: string
          user_id: string
        }
        Insert: {
          bytes_received?: number
          completed_at?: string | null
          connector_account_id?: string | null
          created_at?: string
          id?: string
          items_duplicate?: number
          items_failed?: number
          items_new?: number
          items_seen?: number
          received_at?: string | null
          requested_at?: string | null
          source_type: string
          status?: string
          transfer_kind?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          bytes_received?: number
          completed_at?: string | null
          connector_account_id?: string | null
          created_at?: string
          id?: string
          items_duplicate?: number
          items_failed?: number
          items_new?: number
          items_seen?: number
          received_at?: string | null
          requested_at?: string | null
          source_type?: string
          status?: string
          transfer_kind?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_transfer_jobs_connector_account_id_fkey"
            columns: ["connector_account_id"]
            isOneToOne: false
            referencedRelation: "connector_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          first_name: string | null
          id: string
          last_name: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          first_name?: string | null
          id: string
          last_name?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          first_name?: string | null
          id?: string
          last_name?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      security_audit_events: {
        Row: {
          context_json: Json
          id: string
          occurred_at: string
          type: string
          user_id: string
        }
        Insert: {
          context_json?: Json
          id?: string
          occurred_at?: string
          type: string
          user_id: string
        }
        Update: {
          context_json?: Json
          id?: string
          occurred_at?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      archive_ingest_item: {
        Args: {
          p_checksum_sha256: string
          p_connector_account_id: string
          p_created_at_source?: string
          p_file_size: number
          p_mime_type: string
          p_modified_at_source?: string
          p_original_filename: string
          p_source_item_id: string
          p_source_url?: string
          p_storage_key: string
          p_storage_provider: string
          p_type: Database["public"]["Enums"]["archive_item_type"]
        }
        Returns: Json
      }
      archive_reconcile_sources: {
        Args: {
          p_connector_account_id: string
          p_present_source_item_ids: string[]
        }
        Returns: number
      }
      archive_summary: { Args: never; Returns: Json }
      claim_due_jobs: {
        Args: { p_limit: number; p_worker: string }
        Returns: {
          attempts: number
          bytes_processed: number
          claimed_at: string | null
          claimed_by: string | null
          completed_at: string | null
          connector_account_id: string | null
          created_at: string
          cursor: Json | null
          error_code: string | null
          id: string
          items_archived: number
          items_discovered: number
          items_failed: number
          items_processed: number
          items_skipped: number
          job_type: Database["public"]["Enums"]["job_type"]
          last_error: string | null
          next_archive_at: string | null
          retry_count: number
          run_at: string
          safe_error_message: string | null
          scheduled_at: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["job_status"]
          updated_at: string
          user_id: string
        }[]
        SetofOptions: {
          from: "*"
          to: "archive_jobs"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      claim_job_items: {
        Args: { p_job: string; p_limit: number; p_worker: string }
        Returns: {
          attempts: number
          claimed_at: string | null
          claimed_by: string | null
          connector_account_id: string | null
          created_at: string
          filename: string | null
          id: string
          job_id: string
          last_error: string | null
          mime_type: string | null
          next_attempt_at: string
          size_bytes: number | null
          source_etag: string | null
          source_item_id: string
          status: string
          storage_key: string | null
          updated_at: string
          user_id: string
        }[]
        SetofOptions: {
          from: "*"
          to: "archive_job_items"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      store_connector_credential: {
        Args: {
          p_ciphertext: string
          p_connector_account_id: string
          p_kind: string
          p_scheme: string
        }
        Returns: undefined
      }
    }
    Enums: {
      archive_frequency: "daily" | "weekly" | "monthly"
      archive_item_status: "pending" | "storing" | "archived" | "failed"
      archive_item_type:
        | "photo"
        | "video"
        | "document"
        | "post"
        | "message"
        | "audio"
        | "other"
      connector_account_status:
        | "connected"
        | "archiving"
        | "action_required"
        | "temporary_problem"
        | "disconnected"
      connector_category: "photo_video" | "social" | "documents" | "device"
      connector_type: "live" | "portability" | "archive_importer"
      implementation_status:
        | "research"
        | "verified"
        | "development"
        | "provider_approval"
        | "beta"
        | "production"
        | "disabled"
      job_status:
        | "queued"
        | "running"
        | "completed"
        | "failed"
        | "retrying"
        | "cancelled"
      job_type:
        | "discovery"
        | "initial_import"
        | "incremental_import"
        | "export"
        | "integrity_check"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      archive_frequency: ["daily", "weekly", "monthly"],
      archive_item_status: ["pending", "storing", "archived", "failed"],
      archive_item_type: [
        "photo",
        "video",
        "document",
        "post",
        "message",
        "audio",
        "other",
      ],
      connector_account_status: [
        "connected",
        "archiving",
        "action_required",
        "temporary_problem",
        "disconnected",
      ],
      connector_category: ["photo_video", "social", "documents", "device"],
      connector_type: ["live", "portability", "archive_importer"],
      implementation_status: [
        "research",
        "verified",
        "development",
        "provider_approval",
        "beta",
        "production",
        "disabled",
      ],
      job_status: [
        "queued",
        "running",
        "completed",
        "failed",
        "retrying",
        "cancelled",
      ],
      job_type: [
        "discovery",
        "initial_import",
        "incremental_import",
        "export",
        "integrity_check",
      ],
    },
  },
} as const
